ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules:
      - org.example.ApplicationKt.module

jwt:
  secret: "secret-key"
  issuer: "nobel-api"
  audience: "nobel-clients"
  realm: "Access to Nobel API"
  expirationMinutes: 30
